# -*- coding: utf-8 -*-
"""scrapping_twitter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10pDasnA9OCaMM58xdQ8xZe2XmgmFpqpT
"""

# Ganti dengan auth token akun Anda
twitter_auth_token = "copy_your_token_x_here"

# Install Pandas
!pip install pandas

# Update apt-get dan install sertifikat yang dibutuhkan
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg

# Menambahkan GPG Key NodeSource
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

# Menambahkan repository Node.js v20
!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

# Install Node.js
!sudo apt-get update
!sudo apt-get install nodejs -y

# Cek versi Node.js untuk memastikan instalasi berhasil
!node -v

# Menentukan nama file output dan ID Tweet target
filename = 'data.csv'
target_id = '2040575505964191995'


# Jika ingin memastikan balasannya hanya bahasa Indonesia:
search_keyword = f"conversation_id:{target_id} lang:id"

# Mencari tweet tentang "pemilu" dari 1 Januari 2024 sampai 14 Februari 2024
#search_keyword = "pemilu since:2024-01-01 until:2024-02-14"

# Mencari kata spesifik
#search_keyword = "kecerdasan buatan"

# Mencari hashtag
#search_keyword = "#teknologi"

# Mencari kata "banjir" khusus dalam bahasa Indonesia
#search_keyword = "banjir lang:id"

limit = 500

# Install dependencies untuk browser engine bawaan (Playwright)
!npx playwright install-deps

# Menjalankan tweet-harvest
!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

import pandas as pd

# Menentukan jalur file CSV hasil crawling
file_path = f"tweets-data/{filename}"

# Membaca data ke dalam DataFrame Pandas
df = pd.read_csv(file_path)

# Menampilkan pratinjau data
display(df)

# Menampilkan total tweet yang berhasil diambil
num_tweets = len(df)
print(f'Jumlah tweet yang berhasil diekstrak adalah: {num_tweets}')